version: '3'
services:
  backend:
    build: .
    container_name: "backend"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongodb
      
  mongodb:
    image: "mongo:3.4.1"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null